### ISSUE TITLE
Refatoração do arquivo Program.cs

### ISSUE THREAD

**Issue by jarvmds** [jarvmds/AulaSemana10#1]
Atualmente o código do programa está organizado em um único arquivo, com muitas responsabilidades, tais como:
- Roteamento com base no `args`
- Conexão com o banco de dados
- Criação de tabelas
- Consultas SQL
- Textos que retornam como resposta

Uma possível solução seria criar uma classe responsável por fazer o setup (inicialização do banco de dados, como criar tabelas) do banco de dados, outra classe que representa um Computador (id, ram e processador) e uma classe que abstrai o acesso a dados, com métodos para criar um novo computador e listar computadores cadastrados.

## Tarefas
- [x] Criar a classe de setup do banco de dados
- [x] Implementar a classe Computer
- [x] Implementar a classe de acesso a dados para Computer

**Comment by jarvmds** [comment]
muchos problemas

**Comment by jarvmds** [comment]
> muchos problemas

verdade, concordo

**Comment by sabrina-reis1** [comment]
fake
